BEGIN;

DELETE FROM perfumes WHERE catalog_mode = 'retail';

INSERT INTO perfumes (
  id, catalog_mode, brand, name, family, description,
  tags, notes_top, notes_heart, notes_base,
  seasons, day_night, base_price, base_volume, sillage, longevity,
  image_url, search_name_ru, is_hit, order_count, in_stock, currency,
  popularity, popularity_month, popularity_month_key,
  review_avg, review_count, created_at, updated_at
) VALUES (
  'p-21', 'retail', 'Bakhur', 'Bakhur Creed', '', 'Искрящаяся свежесть...',
  ARRAY['унисекс', 'офис', 'свежий', 'цитрусовый', 'повседневный'], ARRAY['Цитрус', 'Фрукты'], ARRAY['Тропический'], ARRAY['Мускус', 'Кедр'],
  ARRAY['Весна', 'Лето'], ARRAY['День'], 79, 50, 3, 3,
  '/creed.png', '', false, 0, true, '₽',
  0, 0, '',
  0, 0, now(), now()
)
ON CONFLICT (id) DO UPDATE SET
  catalog_mode = EXCLUDED.catalog_mode,
  brand = EXCLUDED.brand,
  name = EXCLUDED.name,
  family = EXCLUDED.family,
  description = EXCLUDED.description,
  tags = EXCLUDED.tags,
  notes_top = EXCLUDED.notes_top,
  notes_heart = EXCLUDED.notes_heart,
  notes_base = EXCLUDED.notes_base,
  seasons = EXCLUDED.seasons,
  day_night = EXCLUDED.day_night,
  base_price = EXCLUDED.base_price,
  base_volume = EXCLUDED.base_volume,
  sillage = EXCLUDED.sillage,
  longevity = EXCLUDED.longevity,
  image_url = EXCLUDED.image_url,
  search_name_ru = EXCLUDED.search_name_ru,
  is_hit = EXCLUDED.is_hit,
  order_count = EXCLUDED.order_count,
  in_stock = EXCLUDED.in_stock,
  currency = EXCLUDED.currency,
  popularity = EXCLUDED.popularity,
  popularity_month = EXCLUDED.popularity_month,
  popularity_month_key = EXCLUDED.popularity_month_key,
  updated_at = now();

INSERT INTO perfumes (
  id, catalog_mode, brand, name, family, description,
  tags, notes_top, notes_heart, notes_base,
  seasons, day_night, base_price, base_volume, sillage, longevity,
  image_url, search_name_ru, is_hit, order_count, in_stock, currency,
  popularity, popularity_month, popularity_month_key,
  review_avg, review_count, created_at, updated_at
) VALUES (
  'p-01', 'retail', 'Marc-Antoine Barrois', 'Ganymede', '', '',
  ARRAY['унисекс', 'нишевый', 'минеральный', 'кожаный', 'офис', 'вечерний'], ARRAY['Мандарин'], ARRAY['Бессмертник (Immortelle)', 'Минеральные ноты', 'Кожаные нюансы'], ARRAY['Аккорды минеральной кожи', 'Солоноватые ноты'],
  ARRAY['Осень', 'Зима', 'Весна'], ARRAY['День', 'Вечер'], 29000, 100, 4, 5,
  '/images/p-01.jpg', '', false, 0, true, '₽',
  0, 0, '',
  0, 0, now(), now()
)
ON CONFLICT (id) DO UPDATE SET
  catalog_mode = EXCLUDED.catalog_mode,
  brand = EXCLUDED.brand,
  name = EXCLUDED.name,
  family = EXCLUDED.family,
  description = EXCLUDED.description,
  tags = EXCLUDED.tags,
  notes_top = EXCLUDED.notes_top,
  notes_heart = EXCLUDED.notes_heart,
  notes_base = EXCLUDED.notes_base,
  seasons = EXCLUDED.seasons,
  day_night = EXCLUDED.day_night,
  base_price = EXCLUDED.base_price,
  base_volume = EXCLUDED.base_volume,
  sillage = EXCLUDED.sillage,
  longevity = EXCLUDED.longevity,
  image_url = EXCLUDED.image_url,
  search_name_ru = EXCLUDED.search_name_ru,
  is_hit = EXCLUDED.is_hit,
  order_count = EXCLUDED.order_count,
  in_stock = EXCLUDED.in_stock,
  currency = EXCLUDED.currency,
  popularity = EXCLUDED.popularity,
  popularity_month = EXCLUDED.popularity_month,
  popularity_month_key = EXCLUDED.popularity_month_key,
  updated_at = now();

INSERT INTO perfumes (
  id, catalog_mode, brand, name, family, description,
  tags, notes_top, notes_heart, notes_base,
  seasons, day_night, base_price, base_volume, sillage, longevity,
  image_url, search_name_ru, is_hit, order_count, in_stock, currency,
  popularity, popularity_month, popularity_month_key,
  review_avg, review_count, created_at, updated_at
) VALUES (
  'p-02', 'retail', 'Louis Vuitton', 'L’Immensité', '', '',
  ARRAY['мужской', 'свежий', 'цитрусовый', 'офис', 'повседневный'], ARRAY['Грейпфрут', 'Имбирь'], ARRAY['Каскалон (водные ноты)'], ARRAY['Амброксан', 'Лабданум', 'Амбра (ambergris)'],
  ARRAY['Весна', 'Лето', 'Осень'], ARRAY['День'], 36000, 100, 3, 4,
  '/images/p-02.jpg', '', false, 0, true, '₽',
  0, 0, '',
  0, 0, now(), now()
)
ON CONFLICT (id) DO UPDATE SET
  catalog_mode = EXCLUDED.catalog_mode,
  brand = EXCLUDED.brand,
  name = EXCLUDED.name,
  family = EXCLUDED.family,
  description = EXCLUDED.description,
  tags = EXCLUDED.tags,
  notes_top = EXCLUDED.notes_top,
  notes_heart = EXCLUDED.notes_heart,
  notes_base = EXCLUDED.notes_base,
  seasons = EXCLUDED.seasons,
  day_night = EXCLUDED.day_night,
  base_price = EXCLUDED.base_price,
  base_volume = EXCLUDED.base_volume,
  sillage = EXCLUDED.sillage,
  longevity = EXCLUDED.longevity,
  image_url = EXCLUDED.image_url,
  search_name_ru = EXCLUDED.search_name_ru,
  is_hit = EXCLUDED.is_hit,
  order_count = EXCLUDED.order_count,
  in_stock = EXCLUDED.in_stock,
  currency = EXCLUDED.currency,
  popularity = EXCLUDED.popularity,
  popularity_month = EXCLUDED.popularity_month,
  popularity_month_key = EXCLUDED.popularity_month_key,
  updated_at = now();

INSERT INTO perfumes (
  id, catalog_mode, brand, name, family, description,
  tags, notes_top, notes_heart, notes_base,
  seasons, day_night, base_price, base_volume, sillage, longevity,
  image_url, search_name_ru, is_hit, order_count, in_stock, currency,
  popularity, popularity_month, popularity_month_key,
  review_avg, review_count, created_at, updated_at
) VALUES (
  'p-03', 'retail', 'Bvlgari', 'Tygar (Le Gemme)', '', '',
  ARRAY['унисекс', 'цитрусовый', 'свежий', 'шлейфовый', 'офис', 'выход'], ARRAY['Грейпфрут'], ARRAY['Имбирь', 'Амбретта'], ARRAY['Амброксан', 'Мускус', 'Ветивер', 'Пачули'],
  ARRAY['Весна', 'Лето', 'Осень'], ARRAY['День', 'Вечер'], 52000, 100, 4, 4,
  '/images/p-03.jpg', '', false, 0, true, '₽',
  0, 0, '',
  0, 0, now(), now()
)
ON CONFLICT (id) DO UPDATE SET
  catalog_mode = EXCLUDED.catalog_mode,
  brand = EXCLUDED.brand,
  name = EXCLUDED.name,
  family = EXCLUDED.family,
  description = EXCLUDED.description,
  tags = EXCLUDED.tags,
  notes_top = EXCLUDED.notes_top,
  notes_heart = EXCLUDED.notes_heart,
  notes_base = EXCLUDED.notes_base,
  seasons = EXCLUDED.seasons,
  day_night = EXCLUDED.day_night,
  base_price = EXCLUDED.base_price,
  base_volume = EXCLUDED.base_volume,
  sillage = EXCLUDED.sillage,
  longevity = EXCLUDED.longevity,
  image_url = EXCLUDED.image_url,
  search_name_ru = EXCLUDED.search_name_ru,
  is_hit = EXCLUDED.is_hit,
  order_count = EXCLUDED.order_count,
  in_stock = EXCLUDED.in_stock,
  currency = EXCLUDED.currency,
  popularity = EXCLUDED.popularity,
  popularity_month = EXCLUDED.popularity_month,
  popularity_month_key = EXCLUDED.popularity_month_key,
  updated_at = now();

INSERT INTO perfumes (
  id, catalog_mode, brand, name, family, description,
  tags, notes_top, notes_heart, notes_base,
  seasons, day_night, base_price, base_volume, sillage, longevity,
  image_url, search_name_ru, is_hit, order_count, in_stock, currency,
  popularity, popularity_month, popularity_month_key,
  review_avg, review_count, created_at, updated_at
) VALUES (
  'p-04', 'retail', 'Clive Christian', 'Jump Up And Kiss Me Hedonistic (2021)', '', '',
  ARRAY['унисекс', 'вечерний', 'для выхода', 'сладкий', 'гурманский', 'вишня', 'табачный'], ARRAY['Чёрная вишня', 'Шалфей', 'Цитрусовые акценты'], ARRAY['Абсент', 'Какао-лист', 'Флоральные ноты'], ARRAY['Амбра', 'Кожа', 'Лабданум', 'Ваниль', 'Бобы тонка', 'Табачные нюансы'],
  ARRAY['Осень', 'Зима'], ARRAY['Вечер', 'Ночь'], 78000, 50, 4, 5,
  '/images/p-04.jpg', '', false, 0, true, '₽',
  0, 0, '',
  0, 0, now(), now()
)
ON CONFLICT (id) DO UPDATE SET
  catalog_mode = EXCLUDED.catalog_mode,
  brand = EXCLUDED.brand,
  name = EXCLUDED.name,
  family = EXCLUDED.family,
  description = EXCLUDED.description,
  tags = EXCLUDED.tags,
  notes_top = EXCLUDED.notes_top,
  notes_heart = EXCLUDED.notes_heart,
  notes_base = EXCLUDED.notes_base,
  seasons = EXCLUDED.seasons,
  day_night = EXCLUDED.day_night,
  base_price = EXCLUDED.base_price,
  base_volume = EXCLUDED.base_volume,
  sillage = EXCLUDED.sillage,
  longevity = EXCLUDED.longevity,
  image_url = EXCLUDED.image_url,
  search_name_ru = EXCLUDED.search_name_ru,
  is_hit = EXCLUDED.is_hit,
  order_count = EXCLUDED.order_count,
  in_stock = EXCLUDED.in_stock,
  currency = EXCLUDED.currency,
  popularity = EXCLUDED.popularity,
  popularity_month = EXCLUDED.popularity_month,
  popularity_month_key = EXCLUDED.popularity_month_key,
  updated_at = now();

INSERT INTO perfumes (
  id, catalog_mode, brand, name, family, description,
  tags, notes_top, notes_heart, notes_base,
  seasons, day_night, base_price, base_volume, sillage, longevity,
  image_url, search_name_ru, is_hit, order_count, in_stock, currency,
  popularity, popularity_month, popularity_month_key,
  review_avg, review_count, created_at, updated_at
) VALUES (
  'p-05', 'retail', 'Clive Christian', 'Blonde Amber (XXI Art Deco)', '', '',
  ARRAY['унисекс', 'вечерний', 'шлейфовый', 'табачный', 'амбровый', 'люкс', 'праздничный'], ARRAY['Горький апельсин', 'Ром', 'Кардамон', 'Розовый перец', 'Бергамот', 'Грейпфрут'], ARRAY['Белый табак', 'Сухофрукты', 'Тубероза', 'Жасмин', 'Ирис (orris)', 'Османтус', 'Сандал'], ARRAY['Амбра', 'Бобы тонка', 'Ваниль', 'Лабданум', 'Мирра', 'Пачули', 'Мускус', 'Кедр', 'Ветивер'],
  ARRAY['Осень', 'Зима'], ARRAY['Вечер', 'Ночь'], 82000, 50, 4, 5,
  '/images/p-05.jpg', '', false, 0, true, '₽',
  0, 0, '',
  0, 0, now(), now()
)
ON CONFLICT (id) DO UPDATE SET
  catalog_mode = EXCLUDED.catalog_mode,
  brand = EXCLUDED.brand,
  name = EXCLUDED.name,
  family = EXCLUDED.family,
  description = EXCLUDED.description,
  tags = EXCLUDED.tags,
  notes_top = EXCLUDED.notes_top,
  notes_heart = EXCLUDED.notes_heart,
  notes_base = EXCLUDED.notes_base,
  seasons = EXCLUDED.seasons,
  day_night = EXCLUDED.day_night,
  base_price = EXCLUDED.base_price,
  base_volume = EXCLUDED.base_volume,
  sillage = EXCLUDED.sillage,
  longevity = EXCLUDED.longevity,
  image_url = EXCLUDED.image_url,
  search_name_ru = EXCLUDED.search_name_ru,
  is_hit = EXCLUDED.is_hit,
  order_count = EXCLUDED.order_count,
  in_stock = EXCLUDED.in_stock,
  currency = EXCLUDED.currency,
  popularity = EXCLUDED.popularity,
  popularity_month = EXCLUDED.popularity_month,
  popularity_month_key = EXCLUDED.popularity_month_key,
  updated_at = now();

INSERT INTO perfumes (
  id, catalog_mode, brand, name, family, description,
  tags, notes_top, notes_heart, notes_base,
  seasons, day_night, base_price, base_volume, sillage, longevity,
  image_url, search_name_ru, is_hit, order_count, in_stock, currency,
  popularity, popularity_month, popularity_month_key,
  review_avg, review_count, created_at, updated_at
) VALUES (
  'p-06', 'retail', 'Marc-Antoine Barrois', 'Tilia', '', '',
  ARRAY['унисекс', 'цветочный', 'светлый', 'повседневный', 'офис', 'романтичный'], ARRAY['Липовый цвет (linden blossom)', 'Жасмин самбак', 'Дрок (broom)'], ARRAY['Гелиотроп', 'Апельсиновый цвет', 'Ветивер'], ARRAY['Ambrofix™', 'Georgywood'],
  ARRAY['Весна', 'Лето'], ARRAY['День', 'Вечер'], 26000, 100, 3, 4,
  '/images/p-06.jpg', '', false, 0, true, '₽',
  0, 0, '',
  0, 0, now(), now()
)
ON CONFLICT (id) DO UPDATE SET
  catalog_mode = EXCLUDED.catalog_mode,
  brand = EXCLUDED.brand,
  name = EXCLUDED.name,
  family = EXCLUDED.family,
  description = EXCLUDED.description,
  tags = EXCLUDED.tags,
  notes_top = EXCLUDED.notes_top,
  notes_heart = EXCLUDED.notes_heart,
  notes_base = EXCLUDED.notes_base,
  seasons = EXCLUDED.seasons,
  day_night = EXCLUDED.day_night,
  base_price = EXCLUDED.base_price,
  base_volume = EXCLUDED.base_volume,
  sillage = EXCLUDED.sillage,
  longevity = EXCLUDED.longevity,
  image_url = EXCLUDED.image_url,
  search_name_ru = EXCLUDED.search_name_ru,
  is_hit = EXCLUDED.is_hit,
  order_count = EXCLUDED.order_count,
  in_stock = EXCLUDED.in_stock,
  currency = EXCLUDED.currency,
  popularity = EXCLUDED.popularity,
  popularity_month = EXCLUDED.popularity_month,
  popularity_month_key = EXCLUDED.popularity_month_key,
  updated_at = now();

INSERT INTO perfumes (
  id, catalog_mode, brand, name, family, description,
  tags, notes_top, notes_heart, notes_base,
  seasons, day_night, base_price, base_volume, sillage, longevity,
  image_url, search_name_ru, is_hit, order_count, in_stock, currency,
  popularity, popularity_month, popularity_month_key,
  review_avg, review_count, created_at, updated_at
) VALUES (
  'p-07', 'retail', 'Arabian Oud', 'Madawi Gold Edition', '', '',
  ARRAY['женский', 'восточный', 'сладкий', 'для выхода', 'шлейфовый', 'ванильный'], ARRAY['Фруктовые ноты', 'Кардамон'], ARRAY['Бобы тонка', 'Жасмин', 'Цветок ананаса'], ARRAY['Ваниль', 'Пачули'],
  ARRAY['Осень', 'Зима', 'Весна'], ARRAY['Вечер', 'Ночь'], 24000, 100, 4, 5,
  '/images/p-07.jpg', '', false, 0, true, '₽',
  0, 0, '',
  0, 0, now(), now()
)
ON CONFLICT (id) DO UPDATE SET
  catalog_mode = EXCLUDED.catalog_mode,
  brand = EXCLUDED.brand,
  name = EXCLUDED.name,
  family = EXCLUDED.family,
  description = EXCLUDED.description,
  tags = EXCLUDED.tags,
  notes_top = EXCLUDED.notes_top,
  notes_heart = EXCLUDED.notes_heart,
  notes_base = EXCLUDED.notes_base,
  seasons = EXCLUDED.seasons,
  day_night = EXCLUDED.day_night,
  base_price = EXCLUDED.base_price,
  base_volume = EXCLUDED.base_volume,
  sillage = EXCLUDED.sillage,
  longevity = EXCLUDED.longevity,
  image_url = EXCLUDED.image_url,
  search_name_ru = EXCLUDED.search_name_ru,
  is_hit = EXCLUDED.is_hit,
  order_count = EXCLUDED.order_count,
  in_stock = EXCLUDED.in_stock,
  currency = EXCLUDED.currency,
  popularity = EXCLUDED.popularity,
  popularity_month = EXCLUDED.popularity_month,
  popularity_month_key = EXCLUDED.popularity_month_key,
  updated_at = now();

INSERT INTO perfumes (
  id, catalog_mode, brand, name, family, description,
  tags, notes_top, notes_heart, notes_base,
  seasons, day_night, base_price, base_volume, sillage, longevity,
  image_url, search_name_ru, is_hit, order_count, in_stock, currency,
  popularity, popularity_month, popularity_month_key,
  review_avg, review_count, created_at, updated_at
) VALUES (
  'p-08', 'retail', 'Tom Ford', 'Ombré Leather (2018)', '', '',
  ARRAY['унисекс', 'кожаный', 'стильный', 'для выхода', 'вечерний', 'характерный'], ARRAY['Кардамон'], ARRAY['Кожа', 'Жасмин самбак'], ARRAY['Амбра', 'Мох', 'Пачули'],
  ARRAY['Осень', 'Зима', 'Весна'], ARRAY['День', 'Вечер'], 23000, 100, 4, 4,
  '/images/p-08.jpg', '', false, 0, true, '₽',
  0, 0, '',
  0, 0, now(), now()
)
ON CONFLICT (id) DO UPDATE SET
  catalog_mode = EXCLUDED.catalog_mode,
  brand = EXCLUDED.brand,
  name = EXCLUDED.name,
  family = EXCLUDED.family,
  description = EXCLUDED.description,
  tags = EXCLUDED.tags,
  notes_top = EXCLUDED.notes_top,
  notes_heart = EXCLUDED.notes_heart,
  notes_base = EXCLUDED.notes_base,
  seasons = EXCLUDED.seasons,
  day_night = EXCLUDED.day_night,
  base_price = EXCLUDED.base_price,
  base_volume = EXCLUDED.base_volume,
  sillage = EXCLUDED.sillage,
  longevity = EXCLUDED.longevity,
  image_url = EXCLUDED.image_url,
  search_name_ru = EXCLUDED.search_name_ru,
  is_hit = EXCLUDED.is_hit,
  order_count = EXCLUDED.order_count,
  in_stock = EXCLUDED.in_stock,
  currency = EXCLUDED.currency,
  popularity = EXCLUDED.popularity,
  popularity_month = EXCLUDED.popularity_month,
  popularity_month_key = EXCLUDED.popularity_month_key,
  updated_at = now();

INSERT INTO perfumes (
  id, catalog_mode, brand, name, family, description,
  tags, notes_top, notes_heart, notes_base,
  seasons, day_night, base_price, base_volume, sillage, longevity,
  image_url, search_name_ru, is_hit, order_count, in_stock, currency,
  popularity, popularity_month, popularity_month_key,
  review_avg, review_count, created_at, updated_at
) VALUES (
  'p-09', 'retail', 'Tom Ford', 'Tobacco Vanille', '', '',
  ARRAY['унисекс', 'табачный', 'ванильный', 'гурманский', 'очень шлейфовый', 'вечерний', 'зимний'], ARRAY['Табачный лист', 'Пряные ноты'], ARRAY['Ваниль', 'Какао', 'Бобы тонка', 'Табачный цвет'], ARRAY['Сухофрукты', 'Древесные ноты'],
  ARRAY['Осень', 'Зима'], ARRAY['Вечер', 'Ночь'], 21000, 50, 5, 5,
  '/images/p-09.jpg', '', false, 0, true, '₽',
  0, 0, '',
  0, 0, now(), now()
)
ON CONFLICT (id) DO UPDATE SET
  catalog_mode = EXCLUDED.catalog_mode,
  brand = EXCLUDED.brand,
  name = EXCLUDED.name,
  family = EXCLUDED.family,
  description = EXCLUDED.description,
  tags = EXCLUDED.tags,
  notes_top = EXCLUDED.notes_top,
  notes_heart = EXCLUDED.notes_heart,
  notes_base = EXCLUDED.notes_base,
  seasons = EXCLUDED.seasons,
  day_night = EXCLUDED.day_night,
  base_price = EXCLUDED.base_price,
  base_volume = EXCLUDED.base_volume,
  sillage = EXCLUDED.sillage,
  longevity = EXCLUDED.longevity,
  image_url = EXCLUDED.image_url,
  search_name_ru = EXCLUDED.search_name_ru,
  is_hit = EXCLUDED.is_hit,
  order_count = EXCLUDED.order_count,
  in_stock = EXCLUDED.in_stock,
  currency = EXCLUDED.currency,
  popularity = EXCLUDED.popularity,
  popularity_month = EXCLUDED.popularity_month,
  popularity_month_key = EXCLUDED.popularity_month_key,
  updated_at = now();

INSERT INTO perfumes (
  id, catalog_mode, brand, name, family, description,
  tags, notes_top, notes_heart, notes_base,
  seasons, day_night, base_price, base_volume, sillage, longevity,
  image_url, search_name_ru, is_hit, order_count, in_stock, currency,
  popularity, popularity_month, popularity_month_key,
  review_avg, review_count, created_at, updated_at
) VALUES (
  'p-10', 'retail', 'Roja', 'Elysium Pour Homme Parfum Cologne', '', '',
  ARRAY['мужской', 'свежий', 'цитрусовый', 'элитный', 'офис', 'летний'], ARRAY['Грейпфрут', 'Лимон', 'Бергамот', 'Лайм', 'Тимьян', 'Полынь'], ARRAY['Ягоды можжевельника', 'Яблоко', 'Чёрная смородина', 'Роза', 'Жасмин'], ARRAY['Амбра (ambergris)', 'Мускус', 'Кожа', 'Кедр', 'Бензоин', 'Ваниль'],
  ARRAY['Весна', 'Лето'], ARRAY['День'], 36000, 100, 3, 3,
  '/images/p-10.jpg', '', false, 0, true, '₽',
  0, 0, '',
  0, 0, now(), now()
)
ON CONFLICT (id) DO UPDATE SET
  catalog_mode = EXCLUDED.catalog_mode,
  brand = EXCLUDED.brand,
  name = EXCLUDED.name,
  family = EXCLUDED.family,
  description = EXCLUDED.description,
  tags = EXCLUDED.tags,
  notes_top = EXCLUDED.notes_top,
  notes_heart = EXCLUDED.notes_heart,
  notes_base = EXCLUDED.notes_base,
  seasons = EXCLUDED.seasons,
  day_night = EXCLUDED.day_night,
  base_price = EXCLUDED.base_price,
  base_volume = EXCLUDED.base_volume,
  sillage = EXCLUDED.sillage,
  longevity = EXCLUDED.longevity,
  image_url = EXCLUDED.image_url,
  search_name_ru = EXCLUDED.search_name_ru,
  is_hit = EXCLUDED.is_hit,
  order_count = EXCLUDED.order_count,
  in_stock = EXCLUDED.in_stock,
  currency = EXCLUDED.currency,
  popularity = EXCLUDED.popularity,
  popularity_month = EXCLUDED.popularity_month,
  popularity_month_key = EXCLUDED.popularity_month_key,
  updated_at = now();

INSERT INTO perfumes (
  id, catalog_mode, brand, name, family, description,
  tags, notes_top, notes_heart, notes_base,
  seasons, day_night, base_price, base_volume, sillage, longevity,
  image_url, search_name_ru, is_hit, order_count, in_stock, currency,
  popularity, popularity_month, popularity_month_key,
  review_avg, review_count, created_at, updated_at
) VALUES (
  'p-11', 'retail', 'Mancera', 'Red Tobacco', '', '',
  ARRAY['унисекс', 'табачный', 'пряный', 'очень стойкий', 'очень шлейфовый', 'вечерний', 'зимний'], ARRAY['Корица', 'Уд', 'Шафран', 'Ладан', 'Мускатный орех', 'Зелёное яблоко', 'Белая груша'], ARRAY['Пачули', 'Жасмин'], ARRAY['Табак', 'Амбра', 'Ветивер', 'Гваяк', 'Сандал', 'Мускус', 'Ваниль'],
  ARRAY['Осень', 'Зима'], ARRAY['Вечер', 'Ночь'], 14000, 120, 5, 5,
  '/images/p-11.jpg', '', false, 0, true, '₽',
  0, 0, '',
  0, 0, now(), now()
)
ON CONFLICT (id) DO UPDATE SET
  catalog_mode = EXCLUDED.catalog_mode,
  brand = EXCLUDED.brand,
  name = EXCLUDED.name,
  family = EXCLUDED.family,
  description = EXCLUDED.description,
  tags = EXCLUDED.tags,
  notes_top = EXCLUDED.notes_top,
  notes_heart = EXCLUDED.notes_heart,
  notes_base = EXCLUDED.notes_base,
  seasons = EXCLUDED.seasons,
  day_night = EXCLUDED.day_night,
  base_price = EXCLUDED.base_price,
  base_volume = EXCLUDED.base_volume,
  sillage = EXCLUDED.sillage,
  longevity = EXCLUDED.longevity,
  image_url = EXCLUDED.image_url,
  search_name_ru = EXCLUDED.search_name_ru,
  is_hit = EXCLUDED.is_hit,
  order_count = EXCLUDED.order_count,
  in_stock = EXCLUDED.in_stock,
  currency = EXCLUDED.currency,
  popularity = EXCLUDED.popularity,
  popularity_month = EXCLUDED.popularity_month,
  popularity_month_key = EXCLUDED.popularity_month_key,
  updated_at = now();

INSERT INTO perfumes (
  id, catalog_mode, brand, name, family, description,
  tags, notes_top, notes_heart, notes_base,
  seasons, day_night, base_price, base_volume, sillage, longevity,
  image_url, search_name_ru, is_hit, order_count, in_stock, currency,
  popularity, popularity_month, popularity_month_key,
  review_avg, review_count, created_at, updated_at
) VALUES (
  'p-12', 'retail', 'Creed', 'Aventus', '', '',
  ARRAY['мужской', 'фруктовый', 'дымный', 'универсальный', 'офис', 'свидание'], ARRAY['Ананас', 'Бергамот', 'Чёрная смородина', 'Яблоко'], ARRAY['Берёза', 'Пачули', 'Жасмин', 'Роза'], ARRAY['Мускус', 'Дубовый мох', 'Амбра', 'Ваниль'],
  ARRAY['Весна', 'Лето', 'Осень'], ARRAY['День', 'Вечер'], 42000, 100, 4, 4,
  '/images/p-12.jpg', '', false, 0, true, '₽',
  0, 0, '',
  0, 0, now(), now()
)
ON CONFLICT (id) DO UPDATE SET
  catalog_mode = EXCLUDED.catalog_mode,
  brand = EXCLUDED.brand,
  name = EXCLUDED.name,
  family = EXCLUDED.family,
  description = EXCLUDED.description,
  tags = EXCLUDED.tags,
  notes_top = EXCLUDED.notes_top,
  notes_heart = EXCLUDED.notes_heart,
  notes_base = EXCLUDED.notes_base,
  seasons = EXCLUDED.seasons,
  day_night = EXCLUDED.day_night,
  base_price = EXCLUDED.base_price,
  base_volume = EXCLUDED.base_volume,
  sillage = EXCLUDED.sillage,
  longevity = EXCLUDED.longevity,
  image_url = EXCLUDED.image_url,
  search_name_ru = EXCLUDED.search_name_ru,
  is_hit = EXCLUDED.is_hit,
  order_count = EXCLUDED.order_count,
  in_stock = EXCLUDED.in_stock,
  currency = EXCLUDED.currency,
  popularity = EXCLUDED.popularity,
  popularity_month = EXCLUDED.popularity_month,
  popularity_month_key = EXCLUDED.popularity_month_key,
  updated_at = now();

INSERT INTO perfumes (
  id, catalog_mode, brand, name, family, description,
  tags, notes_top, notes_heart, notes_base,
  seasons, day_night, base_price, base_volume, sillage, longevity,
  image_url, search_name_ru, is_hit, order_count, in_stock, currency,
  popularity, popularity_month, popularity_month_key,
  review_avg, review_count, created_at, updated_at
) VALUES (
  'p-13', 'retail', 'Ormonde Jayne', 'Montabaco', '', '',
  ARRAY['унисекс', 'табачный', 'ароматный', 'умеренно сладкий', 'офис', 'выход'], ARRAY['Бергамот', 'Апельсин', 'Кардамон'], ARRAY['Роза', 'Фиалка', 'Жасмин', 'Магнолия'], ARRAY['Табак', 'Кожа', 'Амбра', 'Сандал', 'Мох'],
  ARRAY['Весна', 'Осень'], ARRAY['День', 'Вечер'], 24000, 100, 3, 4,
  '/images/p-13.jpg', '', false, 0, true, '₽',
  0, 0, '',
  0, 0, now(), now()
)
ON CONFLICT (id) DO UPDATE SET
  catalog_mode = EXCLUDED.catalog_mode,
  brand = EXCLUDED.brand,
  name = EXCLUDED.name,
  family = EXCLUDED.family,
  description = EXCLUDED.description,
  tags = EXCLUDED.tags,
  notes_top = EXCLUDED.notes_top,
  notes_heart = EXCLUDED.notes_heart,
  notes_base = EXCLUDED.notes_base,
  seasons = EXCLUDED.seasons,
  day_night = EXCLUDED.day_night,
  base_price = EXCLUDED.base_price,
  base_volume = EXCLUDED.base_volume,
  sillage = EXCLUDED.sillage,
  longevity = EXCLUDED.longevity,
  image_url = EXCLUDED.image_url,
  search_name_ru = EXCLUDED.search_name_ru,
  is_hit = EXCLUDED.is_hit,
  order_count = EXCLUDED.order_count,
  in_stock = EXCLUDED.in_stock,
  currency = EXCLUDED.currency,
  popularity = EXCLUDED.popularity,
  popularity_month = EXCLUDED.popularity_month,
  popularity_month_key = EXCLUDED.popularity_month_key,
  updated_at = now();

INSERT INTO perfumes (
  id, catalog_mode, brand, name, family, description,
  tags, notes_top, notes_heart, notes_base,
  seasons, day_night, base_price, base_volume, sillage, longevity,
  image_url, search_name_ru, is_hit, order_count, in_stock, currency,
  popularity, popularity_month, popularity_month_key,
  review_avg, review_count, created_at, updated_at
) VALUES (
  'p-14', 'retail', 'Louis Vuitton', 'Symphony', '', '',
  ARRAY['унисекс', 'свежий', 'цитрусовый', 'летний', 'элитный', 'дневной'], ARRAY['Грейпфрут', 'Бергамот'], ARRAY['Имбирь'], ARRAY['Амброксан', 'Мускус'],
  ARRAY['Весна', 'Лето'], ARRAY['День'], 58000, 100, 4, 4,
  '/images/p-14.jpg', '', false, 0, true, '₽',
  0, 0, '',
  0, 0, now(), now()
)
ON CONFLICT (id) DO UPDATE SET
  catalog_mode = EXCLUDED.catalog_mode,
  brand = EXCLUDED.brand,
  name = EXCLUDED.name,
  family = EXCLUDED.family,
  description = EXCLUDED.description,
  tags = EXCLUDED.tags,
  notes_top = EXCLUDED.notes_top,
  notes_heart = EXCLUDED.notes_heart,
  notes_base = EXCLUDED.notes_base,
  seasons = EXCLUDED.seasons,
  day_night = EXCLUDED.day_night,
  base_price = EXCLUDED.base_price,
  base_volume = EXCLUDED.base_volume,
  sillage = EXCLUDED.sillage,
  longevity = EXCLUDED.longevity,
  image_url = EXCLUDED.image_url,
  search_name_ru = EXCLUDED.search_name_ru,
  is_hit = EXCLUDED.is_hit,
  order_count = EXCLUDED.order_count,
  in_stock = EXCLUDED.in_stock,
  currency = EXCLUDED.currency,
  popularity = EXCLUDED.popularity,
  popularity_month = EXCLUDED.popularity_month,
  popularity_month_key = EXCLUDED.popularity_month_key,
  updated_at = now();

INSERT INTO perfumes (
  id, catalog_mode, brand, name, family, description,
  tags, notes_top, notes_heart, notes_base,
  seasons, day_night, base_price, base_volume, sillage, longevity,
  image_url, search_name_ru, is_hit, order_count, in_stock, currency,
  popularity, popularity_month, popularity_month_key,
  review_avg, review_count, created_at, updated_at
) VALUES (
  'p-15', 'retail', 'Louis Vuitton', 'Imagination', '', '',
  ARRAY['унисекс', 'цитрусовый', 'чайный', 'свежий', 'офис', 'повседневный'], ARRAY['Калабрийский бергамот', 'Апельсин', 'Цитрон'], ARRAY['Имбирь', 'Нероли', 'Корица'], ARRAY['Амброксан', 'Чёрный чай', 'Ладан'],
  ARRAY['Весна', 'Лето'], ARRAY['День'], 36000, 100, 3, 4,
  '/images/p-15.jpg', '', false, 0, true, '₽',
  0, 0, '',
  0, 0, now(), now()
)
ON CONFLICT (id) DO UPDATE SET
  catalog_mode = EXCLUDED.catalog_mode,
  brand = EXCLUDED.brand,
  name = EXCLUDED.name,
  family = EXCLUDED.family,
  description = EXCLUDED.description,
  tags = EXCLUDED.tags,
  notes_top = EXCLUDED.notes_top,
  notes_heart = EXCLUDED.notes_heart,
  notes_base = EXCLUDED.notes_base,
  seasons = EXCLUDED.seasons,
  day_night = EXCLUDED.day_night,
  base_price = EXCLUDED.base_price,
  base_volume = EXCLUDED.base_volume,
  sillage = EXCLUDED.sillage,
  longevity = EXCLUDED.longevity,
  image_url = EXCLUDED.image_url,
  search_name_ru = EXCLUDED.search_name_ru,
  is_hit = EXCLUDED.is_hit,
  order_count = EXCLUDED.order_count,
  in_stock = EXCLUDED.in_stock,
  currency = EXCLUDED.currency,
  popularity = EXCLUDED.popularity,
  popularity_month = EXCLUDED.popularity_month,
  popularity_month_key = EXCLUDED.popularity_month_key,
  updated_at = now();

INSERT INTO perfumes (
  id, catalog_mode, brand, name, family, description,
  tags, notes_top, notes_heart, notes_base,
  seasons, day_night, base_price, base_volume, sillage, longevity,
  image_url, search_name_ru, is_hit, order_count, in_stock, currency,
  popularity, popularity_month, popularity_month_key,
  review_avg, review_count, created_at, updated_at
) VALUES (
  'p-16', 'retail', 'Escentric Molecules', 'Molecule 02', '', '',
  ARRAY['унисекс', 'минималистичный', 'амбровый', 'кожа-мускус', 'офис', 'повседневный'], ARRAY['Ambroxan'], ARRAY['Ambroxan'], ARRAY['Ambroxan'],
  ARRAY['Весна', 'Лето', 'Осень'], ARRAY['День', 'Вечер'], 16000, 100, 2, 3,
  '/images/p-16.jpg', '', false, 0, true, '₽',
  0, 0, '',
  0, 0, now(), now()
)
ON CONFLICT (id) DO UPDATE SET
  catalog_mode = EXCLUDED.catalog_mode,
  brand = EXCLUDED.brand,
  name = EXCLUDED.name,
  family = EXCLUDED.family,
  description = EXCLUDED.description,
  tags = EXCLUDED.tags,
  notes_top = EXCLUDED.notes_top,
  notes_heart = EXCLUDED.notes_heart,
  notes_base = EXCLUDED.notes_base,
  seasons = EXCLUDED.seasons,
  day_night = EXCLUDED.day_night,
  base_price = EXCLUDED.base_price,
  base_volume = EXCLUDED.base_volume,
  sillage = EXCLUDED.sillage,
  longevity = EXCLUDED.longevity,
  image_url = EXCLUDED.image_url,
  search_name_ru = EXCLUDED.search_name_ru,
  is_hit = EXCLUDED.is_hit,
  order_count = EXCLUDED.order_count,
  in_stock = EXCLUDED.in_stock,
  currency = EXCLUDED.currency,
  popularity = EXCLUDED.popularity,
  popularity_month = EXCLUDED.popularity_month,
  popularity_month_key = EXCLUDED.popularity_month_key,
  updated_at = now();

INSERT INTO perfumes (
  id, catalog_mode, brand, name, family, description,
  tags, notes_top, notes_heart, notes_base,
  seasons, day_night, base_price, base_volume, sillage, longevity,
  image_url, search_name_ru, is_hit, order_count, in_stock, currency,
  popularity, popularity_month, popularity_month_key,
  review_avg, review_count, created_at, updated_at
) VALUES (
  'p-17', 'retail', 'Orto Parisi', 'Megamare', '', '',
  ARRAY['унисекс', 'морской', 'солёный', 'очень стойкий', 'очень шлейфовый', 'летний'], ARRAY['Морская соль', 'Бергамот'], ARRAY['Морские ноты', 'Водоросли'], ARRAY['Амбра', 'Мускус', 'Древесные ноты'],
  ARRAY['Лето', 'Весна'], ARRAY['День'], 22000, 50, 5, 5,
  '/images/p-17.jpg', '', false, 0, true, '₽',
  0, 0, '',
  0, 0, now(), now()
)
ON CONFLICT (id) DO UPDATE SET
  catalog_mode = EXCLUDED.catalog_mode,
  brand = EXCLUDED.brand,
  name = EXCLUDED.name,
  family = EXCLUDED.family,
  description = EXCLUDED.description,
  tags = EXCLUDED.tags,
  notes_top = EXCLUDED.notes_top,
  notes_heart = EXCLUDED.notes_heart,
  notes_base = EXCLUDED.notes_base,
  seasons = EXCLUDED.seasons,
  day_night = EXCLUDED.day_night,
  base_price = EXCLUDED.base_price,
  base_volume = EXCLUDED.base_volume,
  sillage = EXCLUDED.sillage,
  longevity = EXCLUDED.longevity,
  image_url = EXCLUDED.image_url,
  search_name_ru = EXCLUDED.search_name_ru,
  is_hit = EXCLUDED.is_hit,
  order_count = EXCLUDED.order_count,
  in_stock = EXCLUDED.in_stock,
  currency = EXCLUDED.currency,
  popularity = EXCLUDED.popularity,
  popularity_month = EXCLUDED.popularity_month,
  popularity_month_key = EXCLUDED.popularity_month_key,
  updated_at = now();

INSERT INTO perfumes (
  id, catalog_mode, brand, name, family, description,
  tags, notes_top, notes_heart, notes_base,
  seasons, day_night, base_price, base_volume, sillage, longevity,
  image_url, search_name_ru, is_hit, order_count, in_stock, currency,
  popularity, popularity_month, popularity_month_key,
  review_avg, review_count, created_at, updated_at
) VALUES (
  'p-18', 'retail', 'Kilian', 'Good Girl Gone Bad', '', '',
  ARRAY['женский', 'цветочный', 'романтичный', 'свидание', 'вечерний', 'элитный'], ARRAY['Османтус', 'Жасмин', 'Майская роза'], ARRAY['Тубероза', 'Нарцисс'], ARRAY['Амбра', 'Кедр'],
  ARRAY['Весна', 'Лето'], ARRAY['День', 'Вечер'], 34000, 50, 3, 4,
  '/images/p-18.jpg', '', false, 0, true, '₽',
  0, 0, '',
  0, 0, now(), now()
)
ON CONFLICT (id) DO UPDATE SET
  catalog_mode = EXCLUDED.catalog_mode,
  brand = EXCLUDED.brand,
  name = EXCLUDED.name,
  family = EXCLUDED.family,
  description = EXCLUDED.description,
  tags = EXCLUDED.tags,
  notes_top = EXCLUDED.notes_top,
  notes_heart = EXCLUDED.notes_heart,
  notes_base = EXCLUDED.notes_base,
  seasons = EXCLUDED.seasons,
  day_night = EXCLUDED.day_night,
  base_price = EXCLUDED.base_price,
  base_volume = EXCLUDED.base_volume,
  sillage = EXCLUDED.sillage,
  longevity = EXCLUDED.longevity,
  image_url = EXCLUDED.image_url,
  search_name_ru = EXCLUDED.search_name_ru,
  is_hit = EXCLUDED.is_hit,
  order_count = EXCLUDED.order_count,
  in_stock = EXCLUDED.in_stock,
  currency = EXCLUDED.currency,
  popularity = EXCLUDED.popularity,
  popularity_month = EXCLUDED.popularity_month,
  popularity_month_key = EXCLUDED.popularity_month_key,
  updated_at = now();

INSERT INTO perfumes (
  id, catalog_mode, brand, name, family, description,
  tags, notes_top, notes_heart, notes_base,
  seasons, day_night, base_price, base_volume, sillage, longevity,
  image_url, search_name_ru, is_hit, order_count, in_stock, currency,
  popularity, popularity_month, popularity_month_key,
  review_avg, review_count, created_at, updated_at
) VALUES (
  'p-19', 'retail', 'Kilian', 'Smoking Hot', '', '',
  ARRAY['унисекс', 'табачный', 'дымный', 'ванильный', 'вечерний', 'для выхода'], ARRAY['Яблоко', 'Дымные ноты'], ARRAY['Корица', 'Табак'], ARRAY['Ваниль', 'Бурбон', 'Амбра'],
  ARRAY['Осень', 'Зима'], ARRAY['Вечер', 'Ночь'], 36000, 50, 4, 4,
  '/images/p-19.jpg', '', false, 0, true, '₽',
  0, 0, '',
  0, 0, now(), now()
)
ON CONFLICT (id) DO UPDATE SET
  catalog_mode = EXCLUDED.catalog_mode,
  brand = EXCLUDED.brand,
  name = EXCLUDED.name,
  family = EXCLUDED.family,
  description = EXCLUDED.description,
  tags = EXCLUDED.tags,
  notes_top = EXCLUDED.notes_top,
  notes_heart = EXCLUDED.notes_heart,
  notes_base = EXCLUDED.notes_base,
  seasons = EXCLUDED.seasons,
  day_night = EXCLUDED.day_night,
  base_price = EXCLUDED.base_price,
  base_volume = EXCLUDED.base_volume,
  sillage = EXCLUDED.sillage,
  longevity = EXCLUDED.longevity,
  image_url = EXCLUDED.image_url,
  search_name_ru = EXCLUDED.search_name_ru,
  is_hit = EXCLUDED.is_hit,
  order_count = EXCLUDED.order_count,
  in_stock = EXCLUDED.in_stock,
  currency = EXCLUDED.currency,
  popularity = EXCLUDED.popularity,
  popularity_month = EXCLUDED.popularity_month,
  popularity_month_key = EXCLUDED.popularity_month_key,
  updated_at = now();

INSERT INTO perfumes (
  id, catalog_mode, brand, name, family, description,
  tags, notes_top, notes_heart, notes_base,
  seasons, day_night, base_price, base_volume, sillage, longevity,
  image_url, search_name_ru, is_hit, order_count, in_stock, currency,
  popularity, popularity_month, popularity_month_key,
  review_avg, review_count, created_at, updated_at
) VALUES (
  'p-20', 'retail', 'Kilian', 'Black Phantom', '', '',
  ARRAY['унисекс', 'гурманский', 'ром', 'кофейный', 'сладкий', 'вечерний', 'клуб'], ARRAY['Ром'], ARRAY['Кофе', 'Ветивер', 'Миндаль'], ARRAY['Тростниковый сахар', 'Карамель', 'Сандал', 'Гелиотроп'],
  ARRAY['Осень', 'Зима'], ARRAY['Вечер', 'Ночь'], 36000, 50, 4, 5,
  '/images/p-20.jpg', '', false, 0, true, '₽',
  0, 0, '',
  0, 0, now(), now()
)
ON CONFLICT (id) DO UPDATE SET
  catalog_mode = EXCLUDED.catalog_mode,
  brand = EXCLUDED.brand,
  name = EXCLUDED.name,
  family = EXCLUDED.family,
  description = EXCLUDED.description,
  tags = EXCLUDED.tags,
  notes_top = EXCLUDED.notes_top,
  notes_heart = EXCLUDED.notes_heart,
  notes_base = EXCLUDED.notes_base,
  seasons = EXCLUDED.seasons,
  day_night = EXCLUDED.day_night,
  base_price = EXCLUDED.base_price,
  base_volume = EXCLUDED.base_volume,
  sillage = EXCLUDED.sillage,
  longevity = EXCLUDED.longevity,
  image_url = EXCLUDED.image_url,
  search_name_ru = EXCLUDED.search_name_ru,
  is_hit = EXCLUDED.is_hit,
  order_count = EXCLUDED.order_count,
  in_stock = EXCLUDED.in_stock,
  currency = EXCLUDED.currency,
  popularity = EXCLUDED.popularity,
  popularity_month = EXCLUDED.popularity_month,
  popularity_month_key = EXCLUDED.popularity_month_key,
  updated_at = now();

COMMIT;